[workspace]
resolver = "2"
members = [
    "app/in-one-weekend",
    "app/the-next-week",
    "core/in-one-weekend",
    "core/the-next-week",
]

[workspace.dependencies]
rayon = "1" # 并行处理

[profile.release]
codegen-units = 1
lto = true
